import type { Sheet } from './types';

/**
 * The five pregenerated characters from the 2022 D&D Starter Set (Dragons of
 * Stormwreck Isle), 1st level, as printed on the official character sheets.
 * The official sheets leave the name blank and carry a narrative background
 * plus a "Personal Goal" instead of trait/ideal/bond/flaw boxes; the backstory
 * text here is a paraphrase in our own words.
 *
 * Where the sheet says "prepare N spells from the class list", the picks
 * marked "table choice" are ours, made within the rules.
 */
export const PREGENS: Record<Sheet['key'], Sheet> = {
  cleric: {
    key: 'cleric',
    className: 'Cleric',
    subclass: 'Life Domain',
    race: 'Hill Dwarf',
    background: 'Soldier',
    alignment: 'Lawful Good',
    size: 'Medium',
    level: 1,
    proficiencyBonus: 2,
    abilities: { str: 14, dex: 8, con: 15, int: 10, wis: 16, cha: 12 },
    saveProficiencies: ['wis', 'cha'],
    skills: { athletics: 'proficient', intimidation: 'proficient', medicine: 'proficient', religion: 'proficient' },
    ac: 18,
    acNote: 'chain mail + shield (disadvantage on Stealth)',
    speed: 25,
    hpMax: 11,
    hitDie: '1d8',
    attacks: [
      { key: 'mace', name: 'Mace', kind: 'melee', toHit: 4, damage: '1d6+2', damageType: 'bludgeoning', reach: 5 },
      { key: 'handaxe', name: 'Handaxe', kind: 'thrown', toHit: 4, damage: '1d6+2', damageType: 'slashing', reach: 5, range: { normal: 20, long: 60 }, ammo: 'handaxe' },
      { key: 'torch', name: 'Burning torch', kind: 'melee', toHit: 4, damage: '1', damageType: 'fire', reach: 5, note: 'improvised; 1 fire damage on a hit — lights oil' },
    ],
    spellcasting: {
      ability: 'wis',
      saveDC: 13,
      attackBonus: 5,
      cantrips: ['light', 'sacred flame', 'thaumaturgy'],
      prepared: ['bless', 'cure wounds', 'guiding bolt', 'healing word'],
      known: ['bless', 'cure wounds', 'guiding bolt', 'healing word', 'shield of faith', 'sanctuary', 'detect evil and good'],
      slots: { 1: 2 },
      note: 'Always has bless and cure wounds prepared; guiding bolt and healing word are today\'s table choice.',
    },
    features: [
      'Disciple of Life: healing spells of 1st level or higher restore 2 + the spell\'s level extra HP',
      'Ritual Casting',
      'Spellcasting (Wisdom)',
    ],
    racialTraits: ['Darkvision 60 ft.', 'Dwarven Resilience (advantage on saves vs poison, resistance to poison damage)', 'Stonecunning', 'Dwarven Toughness (+1 HP per level)', 'Heavy armor does not reduce speed'],
    languages: ['Common', 'Dwarvish', 'Elvish', 'Goblin'],
    gold: 10,
    gear: ['chain mail', 'shield', 'mace', 'handaxe', 'holy symbol of Marthammor Duin', 'backpack', 'bedroll', 'mess kit', 'tinderbox', '10 torches', '10 days of rations', 'waterskin', '50 ft. hempen rope', 'insignia of rank', 'broken blade (trophy)', 'bone dice', 'common clothes', 'belt pouch'],
    consumables: { handaxe: 1, torch: 10 },
    resources: {},
    backstory:
      'Trained on the island of Mintarn and served in Neverwinter\'s army and watch as a mercenary, until the work stopped feeling like service. Lately dreams of a shadow swallowing an island, and follows that dream to Stormwreck Isle.',
    personalGoal: 'Banish a Shadow of Death',
    personalGoalText: 'Find the shadow from the dream and drive it off the island.',
    personaHints: ['healer', 'protector', 'faith', 'dwarf', 'soldier', 'god', 'temple', 'priest', 'zeus', 'thunder', 'father'],
    glyph: '✚',
  },
  fighter: {
    key: 'fighter',
    className: 'Fighter',
    subclass: 'Champion',
    race: 'Wood Elf',
    background: 'Folk Hero',
    alignment: 'Neutral Good',
    size: 'Medium',
    level: 1,
    proficiencyBonus: 2,
    abilities: { str: 13, dex: 17, con: 14, int: 10, wis: 13, cha: 8 },
    saveProficiencies: ['str', 'con'],
    skills: { acrobatics: 'proficient', animalHandling: 'proficient', perception: 'proficient', survival: 'proficient' },
    ac: 14,
    acNote: 'leather armor',
    speed: 35,
    hpMax: 12,
    hitDie: '1d10',
    attacks: [
      { key: 'greatsword', name: 'Greatsword', kind: 'melee', toHit: 3, damage: '2d6+1', damageType: 'slashing', reach: 5 },
      { key: 'longbow', name: 'Longbow', kind: 'ranged', toHit: 7, damage: '1d8+3', damageType: 'piercing', range: { normal: 150, long: 600 }, ammo: 'arrow', note: 'includes Archery fighting style (+2)' },
    ],
    features: ['Second Wind (bonus action, regain 1d10 + fighter level HP, once per short rest)', 'Fighting Style: Archery (+2 to ranged weapon attacks)'],
    racialTraits: ['Darkvision 60 ft.', 'Fey Ancestry', 'Trance', 'Mask of the Wild'],
    languages: ['Common', 'Dwarvish', 'Elvish', 'Halfling'],
    gold: 10,
    gear: ['leather armor', 'longbow', '20 arrows', 'greatsword', 'backpack', 'bedroll', 'mess kit', 'tinderbox', '10 torches', '10 days of rations', 'waterskin', '50 ft. hempen rope', 'shovel', 'iron pot', 'common clothes', 'belt pouch'],
    consumables: { arrow: 20, torch: 10 },
    resources: { secondWind: 1 },
    backstory:
      'Family fled Thundertree when Mount Hotenow erupted; grew up a dock carpenter in Neverwinter and became a local hero by standing up to a cruel ship\'s captain. Comes to the island to ask Elder Runara what that courage is for.',
    personalGoal: 'Determine Your Destiny',
    personalGoalText: 'Seek Elder Runara\'s insight into what you are meant to do.',
    personaHints: ['warrior', 'archer', 'soldier', 'hero', 'elf', 'ranger', 'hunter', 'captain', 'knight', 'batman', 'vigilante'],
    glyph: '⚔',
  },
  paladin: {
    key: 'paladin',
    className: 'Paladin',
    subclass: 'Oath of Devotion (from 3rd level)',
    race: 'Human',
    background: 'Noble',
    alignment: 'Lawful Good',
    size: 'Medium',
    level: 1,
    proficiencyBonus: 2,
    abilities: { str: 16, dex: 9, con: 15, int: 11, wis: 13, cha: 14 },
    saveProficiencies: ['wis', 'cha'],
    skills: { athletics: 'proficient', history: 'proficient', insight: 'proficient', persuasion: 'proficient' },
    ac: 18,
    acNote: 'chain mail + shield',
    speed: 30,
    hpMax: 12,
    hitDie: '1d10',
    attacks: [
      { key: 'battleaxe', name: 'Battleaxe', kind: 'melee', toHit: 5, damage: '1d8+3', damageType: 'slashing', reach: 5, note: '1d10+3 two-handed without the shield' },
      { key: 'javelin', name: 'Javelin', kind: 'thrown', toHit: 5, damage: '1d6+3', damageType: 'piercing', reach: 5, range: { normal: 30, long: 120 }, ammo: 'javelin' },
    ],
    features: ['Divine Sense', 'Lay on Hands (pool of 5 HP; touch; no effect on undead or constructs)'],
    racialTraits: ['+1 to every ability score (already included)'],
    languages: ['Common', 'Draconic', 'Dwarvish', 'Giant'],
    gold: 25,
    gear: ['chain mail', 'battleaxe', 'shield', '5 javelins', 'holy symbol of Bahamut', 'fine clothes', 'signet ring', 'scroll of pedigree', 'backpack', 'bedroll', 'mess kit', 'tinderbox', '10 torches', '10 days of rations', 'waterskin', '50 ft. hempen rope', 'belt pouch'],
    consumables: { javelin: 5, torch: 10 },
    resources: { layOnHands: 5 },
    backstory:
      'Born to the rulers of Corlinn Hill northeast of Neverwinter, which Mount Hotenow took; raised in a Waterdeep townhouse and sworn to Bahamut as a champion of the overlooked. Shaken by corruption close to home, and comes to Dragon\'s Rest to be renewed.',
    personalGoal: 'Rejuvenating Pilgrimage',
    personalGoalText: 'Complete a pilgrimage to the temple of Bahamut at Dragon\'s Rest.',
    personaHints: ['knight', 'justice', 'noble', 'honor', 'paladin', 'holy', 'king', 'lord', 'batman', 'guardian', 'superhero'],
    glyph: '🛡',
  },
  rogue: {
    key: 'rogue',
    className: 'Rogue',
    subclass: 'Thief (from 3rd level)',
    race: 'Lightfoot Halfling',
    background: 'Criminal',
    alignment: 'Chaotic Good',
    size: 'Small',
    level: 1,
    proficiencyBonus: 2,
    abilities: { str: 8, dex: 16, con: 12, int: 13, wis: 10, cha: 16 },
    saveProficiencies: ['dex', 'int'],
    skills: { acrobatics: 'proficient', deception: 'proficient', perception: 'proficient', sleightOfHand: 'proficient', stealth: 'expertise' },
    ac: 14,
    acNote: 'leather armor',
    speed: 25,
    hpMax: 9,
    hitDie: '1d8',
    attacks: [
      { key: 'dagger', name: 'Dagger', kind: 'thrown', toHit: 5, damage: '1d4+3', damageType: 'piercing', reach: 5, range: { normal: 20, long: 60 } },
      { key: 'shortbow', name: 'Shortbow', kind: 'ranged', toHit: 5, damage: '1d6+3', damageType: 'piercing', range: { normal: 80, long: 320 }, ammo: 'arrow' },
      { key: 'oil', name: 'Flask of oil (thrown)', kind: 'thrown', toHit: 5, damage: '0', damageType: 'fire', range: { normal: 20, long: 20 }, ammo: 'oil', note: 'improvised weapon; on a hit the target is covered in oil and takes +5 fire the next time it takes fire damage within a minute' },
    ],
    features: ['Sneak Attack 1d6 (advantage, or an ally within 5 ft. of the target)', 'Expertise (Stealth, thieves\' tools)', 'Thieves\' Cant'],
    racialTraits: ['Lucky (reroll a natural 1 on attacks, checks and saves)', 'Brave', 'Halfling Nimbleness', 'Naturally Stealthy'],
    languages: ['Common', 'Goblin', 'Halfling'],
    gold: 15,
    gear: ['leather armor', 'shortbow', '20 arrows', '2 daggers', 'thieves\' tools', 'backpack', 'bag of 1,000 ball bearings', '10 ft. of string', 'bell', '5 candles', '2 crowbars', 'hammer', '10 pitons', 'hooded lantern', '2 flasks of oil', '5 days of rations', 'tinderbox', 'waterskin', '50 ft. hempen rope', 'dark common clothes with a hood', 'belt pouch'],
    consumables: { arrow: 20, dagger: 2, oil: 2 },
    resources: { lucky: 99 },
    backstory:
      'Ran with the Gilded Gallows thieves\' guild until a partner fled with the guild\'s fortune. Word has it the traitor hid it somewhere on Stormwreck Isle, at the cloister called Dragon\'s Rest.',
    personalGoal: 'Find the Lost Fortune',
    personalGoalText: 'Recover the fortune the traitor hid at Dragon\'s Rest.',
    personaHints: ['pirate', 'thief', 'rogue', 'sneaky', 'blackbeard', 'trickster', 'charming', 'smuggler', 'scoundrel', 'halfling', 'clown', 'joker'],
    glyph: '🗡',
  },
  wizard: {
    key: 'wizard',
    className: 'Wizard',
    subclass: 'School of Evocation (from 2nd level)',
    race: 'High Elf',
    background: 'Sage',
    alignment: 'Neutral Good',
    size: 'Medium',
    level: 1,
    proficiencyBonus: 2,
    abilities: { str: 10, dex: 15, con: 14, int: 16, wis: 12, cha: 8 },
    saveProficiencies: ['int', 'wis'],
    skills: { arcana: 'proficient', history: 'proficient', insight: 'proficient', investigation: 'proficient', perception: 'proficient' },
    ac: 12,
    acNote: 'no armor (15 with mage armor)',
    speed: 30,
    hpMax: 8,
    hitDie: '1d6',
    attacks: [
      { key: 'shortsword', name: 'Shortsword', kind: 'melee', toHit: 4, damage: '1d6+2', damageType: 'piercing', reach: 5 },
    ],
    spellcasting: {
      ability: 'int',
      saveDC: 13,
      attackBonus: 5,
      cantrips: ['mage hand', 'prestidigitation', 'ray of frost', 'shocking grasp'],
      prepared: ['magic missile', 'mage armor', 'sleep', 'thunderwave'],
      known: ['detect magic', 'mage armor', 'magic missile', 'shield', 'sleep', 'thunderwave'],
      slots: { 1: 2 },
      note: 'Spellbook holds six spells; four prepared today are the table choice. Arcane Recovery, Ritual Casting.',
    },
    features: ['Arcane Recovery', 'Ritual Casting', 'Spellcasting (Intelligence)'],
    racialTraits: ['Darkvision 60 ft.', 'Fey Ancestry', 'Trance', 'Extra cantrip (prestidigitation)'],
    languages: ['Common', 'Celestial', 'Draconic', 'Dwarvish', 'Elvish'],
    gold: 10,
    gear: ['shortsword', 'component pouch', 'spellbook', 'backpack', 'book of lore', '2 bottles of ink', 'ink pen', '10 sheets of parchment', 'little bag of sand', 'small knife', 'letter from a dead colleague', 'common clothes', 'belt pouch'],
    consumables: {},
    resources: {},
    backstory:
      'Apprenticed in Neverwinter. A colleague\'s letter pointed to an arcane observatory on Stormwreck Isle; then the colleague died, and nobody could say how. The letter is in the pack.',
    personalGoal: 'Discover Lost Knowledge',
    personalGoalText: 'Find the observatory the letter describes and learn what your colleague found.',
    personaHints: ['wizard', 'mage', 'scholar', 'sage', 'arcane', 'magic', 'zeus', 'lightning', 'genius', 'scientist', 'inventor', 'professor'],
    glyph: '✦',
  },
};

export const SHEET_KEYS = Object.keys(PREGENS) as Sheet['key'][];
