#!/usr/bin/env bash
# pull-env.sh — Pull secrets from AWS SSM + Firebase CLI into .env.local files
#
# Run this once after cloning, or whenever SSM values change:
#   bash scripts/pull-env.sh
#
# Requires:
#   - AWS CLI configured (aws configure, or AWS_PROFILE / instance role)
#   - Firebase CLI installed and logged in (firebase login)
#
# Creates:
#   .env.local                   (root — for scripts/tools)
#   www/.env.local               (Vite website)
#   app/desktop/.env.local       (Vite desktop renderer)
#   firebase/functions/.env.local (Cloud Functions local emulator)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

echo ""
echo "🎭 Maskord — Pulling environment variables from SSM + Firebase"
echo ""

# ─── AWS SSM Parameters ───────────────────────────────────────────────────────

echo "🔑 Fetching AWS credentials from SSM (/global)..."

AWS_ACCESS_KEY_ID=$(aws ssm get-parameter \
  --name "/global/AWS_ACCESS_KEY_ID" \
  --with-decryption \
  --query "Parameter.Value" \
  --output text)

AWS_SECRET_ACCESS_KEY=$(aws ssm get-parameter \
  --name "/global/AWS_SECRET_ACCESS_KEY" \
  --with-decryption \
  --query "Parameter.Value" \
  --output text)

echo "✅ AWS credentials fetched"

# ─── Firebase Service Account ─────────────────────────────────────────────────

echo "🔑 Fetching Firebase service account from SSM (/masky/production)..."

FIREBASE_SERVICE_ACCOUNT=$(aws ssm get-parameter \
  --name "/masky/production/firebase_service_account" \
  --with-decryption \
  --query "Parameter.Value" \
  --output text)

echo "✅ Firebase service account fetched"

# ─── Firebase Web SDK Config ──────────────────────────────────────────────────

echo "🔥 Fetching Firebase web SDK config (maskydotnet)..."

FIREBASE_JSON=$(firebase apps:sdkconfig web \
  --project maskydotnet \
  --json 2>/dev/null | python3 -c "
import sys, json
raw = sys.stdin.read()
# firebase CLI wraps output in {result: {...}}
data = json.loads(raw)
cfg = data.get('result', data.get('sdkConfig', data))
print(json.dumps(cfg))
" 2>/dev/null || echo '{}')

# Parse individual values from JSON
parse() { echo "$FIREBASE_JSON" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('$1',''))" 2>/dev/null; }

FIREBASE_API_KEY=$(parse apiKey)
FIREBASE_AUTH_DOMAIN=$(parse authDomain)
FIREBASE_DATABASE_URL=$(parse databaseURL)
FIREBASE_PROJECT_ID=$(parse projectId)
FIREBASE_STORAGE_BUCKET=$(parse storageBucket)
FIREBASE_MESSAGING_SENDER_ID=$(parse messagingSenderId)
FIREBASE_APP_ID=$(parse appId)

# Fallback to known values if firebase CLI parsing fails
FIREBASE_API_KEY="${FIREBASE_API_KEY:-AIzaSyBxDknJ0YcbfGXcrj9aoqyW5UMQm4OhcdI}"
FIREBASE_AUTH_DOMAIN="${FIREBASE_AUTH_DOMAIN:-maskydotnet.firebaseapp.com}"
FIREBASE_DATABASE_URL="${FIREBASE_DATABASE_URL:-https://maskydotnet-default-rtdb.firebaseio.com}"
FIREBASE_PROJECT_ID="${FIREBASE_PROJECT_ID:-maskydotnet}"
FIREBASE_STORAGE_BUCKET="${FIREBASE_STORAGE_BUCKET:-maskydotnet.firebasestorage.app}"
FIREBASE_MESSAGING_SENDER_ID="${FIREBASE_MESSAGING_SENDER_ID:-253806012115}"
FIREBASE_APP_ID="${FIREBASE_APP_ID:-1:253806012115:web:634bb43405ca639401d626}"

echo "✅ Firebase config fetched"

# ─── Write .env.local files ───────────────────────────────────────────────────

write_env() {
  local path="$1"
  local content="$2"
  echo "$content" > "$path"
  echo "   ✓ wrote $path"
}

FIREBASE_VITE_BLOCK="VITE_FIREBASE_API_KEY=${FIREBASE_API_KEY}
VITE_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
VITE_FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
VITE_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
VITE_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
VITE_FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
VITE_FIREBASE_APP_ID=${FIREBASE_APP_ID}"

FIREBASE_BLOCK="FIREBASE_API_KEY=${FIREBASE_API_KEY}
FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
FIREBASE_APP_ID=${FIREBASE_APP_ID}"

echo ""
echo "📝 Writing .env.local files..."

# Root (for scripts)
write_env "${REPO_ROOT}/.env.local" "# Root .env.local — generated by scripts/pull-env.sh — DO NOT COMMIT
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
AWS_REGION=us-east-1
S3_BUCKET=maskord-website-prod
${FIREBASE_BLOCK}"

# www (Vite website)
write_env "${REPO_ROOT}/www/.env.local" "# www/.env.local — generated by scripts/pull-env.sh — DO NOT COMMIT
${FIREBASE_VITE_BLOCK}"

# app/desktop (Vite Electron renderer)
write_env "${REPO_ROOT}/app/desktop/.env.local" "# app/desktop/.env.local — generated by scripts/pull-env.sh — DO NOT COMMIT
${FIREBASE_VITE_BLOCK}"

# firebase/functions (Cloud Functions emulator)
# Write service account to a gitignored JSON file too
SA_FILE="${REPO_ROOT}/firebase/functions/service-account.json"
echo "${FIREBASE_SERVICE_ACCOUNT}" > "${SA_FILE}"
echo "   ✓ wrote firebase/functions/service-account.json"

write_env "${REPO_ROOT}/firebase/functions/.env.local" "# firebase/functions/.env.local — generated by scripts/pull-env.sh — DO NOT COMMIT
${FIREBASE_BLOCK}
GOOGLE_APPLICATION_CREDENTIALS=./service-account.json"

# ─── Done ─────────────────────────────────────────────────────────────────────

echo ""
echo "✅ All done! .env.local files are ready for local development."
echo "   These files are gitignored and will not be committed."
echo ""
echo "   Next: npm run dev:web  |  npm run dev:desktop  |  cd app/mobile && expo start"
echo ""
